name: simple
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
      environment:
        type: choice
        options:
          - Development
          - Production
jobs:
  build:
    runs-on:
      - self-hosted
      - my-own-runner # label
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo Hello world
          sleep 15
          echo Goodbye
